### ISSUE TITLE
no such file to load -- flame_channel_parser

### ISSUE THREAD

**Issue by maxnbk** [guerilla-di/tracksperanto#3]
Indeed I see no such file in the structure of either the release or the source. v3.5.8

~/tracksperanto-3.5.8$ ./bin/tracksperanto --help
Starting Tracksperanto. For information and support please contact info@guerilla-di.org
./bin/../lib/import/flame_stabilizer.rb:2:in `require': no such file to load -- flame_channel_parser (LoadError)
        from ./bin/../lib/import/flame_stabilizer.rb:2
        from ./bin/../lib/tracksperanto.rb:119:in `require'
        from ./bin/../lib/tracksperanto.rb:119
        from ./bin/../lib/tracksperanto.rb:118:in `each'
        from ./bin/../lib/tracksperanto.rb:118
        from ./bin/tracksperanto:17:in `require'
        from ./bin/tracksperanto:17

Not using gem install as limitation of environment, might be part of the problem but neither do I see the file in question.

**Comment by julik** [comment]
> Not using gem install as limitation of environment

How are you installing Tracksperanto? It has other gems as dependencies, and they need to be installed _and_ be on the loadpath for the software to function.

**Comment by maxnbk** [comment]
Yeah I was looking further into it and it looks like there's a dependency that requires ruby-2 (despite tracksperanto itself requiring only ruby 1.8.3+) and was breaking the install. Closing until I can get ruby-2 on the system in question to test. But should mark tracksperanto as requiring ruby-2 now as a result of the dependency.

**Comment by julik** [comment]
Can you open an issue for that? What was the dependency that required Ruby 2? I was planning obsoleting 1.8 support for quite a while but it hasn't been done yet. 1.83 is even older than what Tracksperanto supports officially (1.8.7).

**Comment by maxnbk** [comment]
tins is the dependency;
I'm on ruby-1.9.3
Mixed up 1.8.3/1.9.3 vs 1.8.7 declared.
