### ISSUE TITLE
tracksperanto requires ruby 2 - docs say 1.8.7

### ISSUE THREAD

**Issue by maxnbk** [guerilla-di/tracksperanto#4]
partial result of gem install tracksperanto -v 3.5.8

Fetching: tins-1.11.0.gem (100%)
ERROR:  Error installing tracksperanto:
        tins requires Ruby version >= 2.0.

**Comment by julik** [comment]
I have just pushed `ruby-187-compat`, can you try that?

**Comment by maxnbk** [comment]
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: tracksperanto requires tins (< 0.9.0); term-ansicolor requires tins (~> 1.0)

**Comment by julik** [comment]
And now?

**Comment by maxnbk** [comment]
built/installed with no errors!
Had trouble running it for a moment but it was my env.
At least I've got to the help doc now which was furthest I've been. Will mark resolved and post back if I have other issues.
Thanks for the quick solve!

**Comment by julik** [comment]
👍
